import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import favicon from "../public/images/favicon.ico";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Docurer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:image" content={favicon} />
      </Head>
      <main>
        
      </main>
    </>
  );
}
